config/routes.rb
Rails.application.routes.draw do
  root 'login#index'

  resources :professors, except: %i[edit create update destroy] do
    collection { get 'search' }
    get '/courses/:course_id', to: 'professors#show_course', as: 'course'
  end
  resources :courses, except: %i[edit create update destroy] do
    collection { get 'search' }
  end
  get 'login' => 'login#index'
  delete '/logout', to: 'sessions#destroy'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'search' => 'search#index'

  resources :reviews, except: %i[index] do
    post '/report' => 'reviews#report'
    put 'upvote', to: 'reviews#upvote'
    put 'downvote', to: 'reviews#downvote'
  end
  resources :sessions, only: %i[create delete]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/partials/_footer.html.erb
<footer>
    <p>© 2020 picachu,  all rights reserved</p>
</footer>

app/views/partials/_nav.html.erb
<div class="navbar">
  <%= link_to search_path do %>
    <%= image_tag 'picachu-logo.png', class: 'img-logo' %>
  <% end %>

  <a href="javascript:void(0)" class="nav-user" id="navUser" onclick="toggleDropdown();">
    <% if current_user %>
      <p><%= current_user.name %></p>
    <% else %>
      <p>Not Logged In</p>
    <% end %>
    <%= image_tag 'arr-down.png', class: 'down-arrow', id: 'nav-arrow' %>
  </a>
  <div class="dropdown" id="profileDropdown" style='display: none'>
    <% if current_user %>
      <%= link_to 'Log Out', logout_path, method: :delete %>    
    <% else %> 
      <%= link_to 'Log In', login_path %>
    <%end%>
  </div>

</div>

<script>
    open = false;

    function rotate180(rotate) {
        if (rotate) {
            document.getElementById('nav-arrow').style.transform = 'rotate(180deg)';
        } else {
            document.getElementById('nav-arrow').style.transform = 'rotate(0deg)';
        }
    }

    function toggleDropdown() {
        open = !open;
        rotate180(open);

        if (open) {
            document.getElementById('profileDropdown').style.display = 'block';
        } else {
            document.getElementById('profileDropdown').style.display = 'none';
        }
    }

</script>

app/views/partials/_report_modal.html.erb
<button class="btn-report" id="open-modal-btn" onclick="openModal()">
  <p><%= image_tag 'flag.svg' %> Report</p>
</button>
<div id="report-modal" class="modal">
  <div class="modal-content">
    <span id="close-modal-btn" class="close">&times;</span>
    <div class="header">
      <h1>Report Review</h1>
      <h3>Please let us know why this review is being reported.</h3>
    </div>
    <form class="wrapper-class" accept-charset="UTF-8" id="reportForm" data-remote="true" method="post" action="<%= review_report_path(review_id) %>">
      <input type="hidden" id="review-id" name="id" value="<%= review_id %>">
      <input type="radio" id="spam" name="reason" value="spamAbusive" onclick="requireOtherInputIfNeeded(this)"
             required>
      <label for="spam">It is spam or abusive.</label><br><br>
      <input type="radio" id="inappropriate" name="reason" value="inappropriateOffensive"
             onclick="requireOtherInputIfNeeded(this)" required>
      <label for="inappropriate">It uses inappropriate or offensive language.</label><br><br>

      <input type="radio" id="other" name="reason" value="other" onclick="requireOtherInputIfNeeded(this)"
             required>
      <label for="other">Other</label><br>
      <input type="text" id="reasonForOther" name="other_input" placeholder="Please specify for 'Other'" disabled><br><br>
      <input class="btn btn-primary w-30" type="submit" value="Submit Report" id="reportReview"/>
    </form>
  </div>
</div>
<%= javascript_include_tag "reportModal", "data-turbolinks-track" => true %>

app/views/partials/_searchcontainers.html.erb
<br>

<div class="radio-container">
    <div class="radio-elem" onclick="showSearch('Professor');">
        <input type="radio" id="radioProfessor" name="searchby" value="professor" checked>
        <label for="radioProfessor" id="labelProfessor" class="radio-label active">Professor</label>
    </div>
    <div class="radio-elem" onclick="showSearch('Course');">
        <input type="radio" id="radioCourse" name="searchby" value="course">
        <label for="radioCourse" id="labelCourse" class="radio-label">Course</label>
    </div>
</div>

<div class="search-container" id="searchProfessor">
    <form method="get" action="<%= search_professors_path %>">
        <input type="text" placeholder="John Doe" name="q[full_name_cont]" id="profName">
        <button type="submit" class="btn btn-primary btn-search">Search</button>
    </form>
</div>

<div class="search-container" id="searchCourse" style="display:none">
    <form method="get" action="<%= search_courses_path %>">
        <input type="text" placeholder="CSCE 431 Parallel Computing" name="q[full_name_cont]" id="courseID">
        <button type="submit" class="btn btn-secondary btn-search">Search</button>
    </form>
</div>

<br>

<%= javascript_include_tag "showSearch", "data-turbolinks-track" => true %>