config/routes.rb
Rails.application.routes.draw do
  root 'login#index'

  resources :professors, except: %i[edit create update destroy] do
    collection { get 'search' }
    get '/courses/:course_id', to: 'professors#show_course', as: 'course'
  end
  resources :courses, except: %i[edit create update destroy] do
    collection { get 'search' }
  end
  get 'login' => 'login#index'
  delete '/logout', to: 'sessions#destroy'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'search' => 'search#index'

  resources :reviews, except: %i[index] do
    post '/report' => 'reviews#report'
    put 'upvote', to: 'reviews#upvote'
    put 'downvote', to: 'reviews#downvote'
  end
  resources :sessions, only: %i[create delete]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/professor.rb
# frozen_string_literal: true

class Professor < ApplicationRecord
  def self.ransortable_attributes(_auth_object = nil)
    column_names
  end

  def self.ransackable_attributes(_auth_object = nil)
    ransortable_attributes
  end
end

app/controllers/professors_controller.rb
# frozen_string_literal: true

class ProfessorsController < ApplicationController
  before_action :set_professor, only: %i[show edit update destroy]
  before_action :set_course, only: %i[show_course]
  helper_method :avg_rev
  # GET /professors
  # GET /professors.json
  def index
    @professors = Professor.all.order(:full_name)
  end

  # GET /professors/1
  # GET /professors/1.json
  def avg_rev(reviews)
    sum = 0
    reviews.each { |a| sum += a.overall_rating }
    sum.to_f / reviews.length
  end

  def show
    @avg_review =
      if @professor.reviews.blank?
        0
      else
        @professor.reviews.average(:overall_rating).round(2)
      end

    @num_reviews = @professor.reviews.length
    @grouped_courses = @professor.reviews.group_by(&:course)
    @courses_with_ratings =
      @grouped_courses.map do |course, reviews|
        [course, reviews.sum(&:overall_rating).to_f / reviews.length]
      end

    @highest_rated_course, _rating =
      @courses_with_ratings.max { |a, b| a[1] <=> b[1] }

    if !@highest_rated_course.blank? && !@highest_rated_course.reviews.blank?
      @highest_rated_course_review =
        @highest_rated_course.reviews.order('overall_rating DESC').first
    end

    @lowest_rated_course, _rating =
      @courses_with_ratings.min { |a, b| a[1] <=> b[1] }

    if !@lowest_rated_course.blank? && !@lowest_rated_course.reviews.blank?
      @lowest_rated_course_review =
        @lowest_rated_course.reviews.order('overall_rating').first
    end

    @highest_rating = 0
    @highest_rating_compo = 5
    @lowest_rating = 0
    @lowest_rating_compo = 5
    unless @highest_rated_course_review.blank?
      @highest_rating = @highest_rated_course_review.overall_rating.floor
      @highest_rating_compo = 5 - @highest_rating
    end
    unless @lowest_rated_course_review.blank?
      @lowest_rating = @lowest_rated_course_review.overall_rating.floor
      @lowest_rating_compo = 5 - @lowest_rating
    end
    # Need overall review rating of particular course caught by the professor
  end

  # GET /professors/1/courses/1
  # GET /professors/1/courses/1.json
  def show_course
    @professor = Professor.find(params[:professor_id])
    @grouped_courses = @professor.reviews.group_by(&:course)
    @course_reviews =
      @professor.reviews.where(course_id: @course.id).order(
        cached_weighted_average: :desc
      )
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit; end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html do
          redirect_to @professor, notice: 'Professor was successfully created.'
        end
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json do
          render json: @professor.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html do
          redirect_to @professor, notice: 'Professor was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit }
        format.json do
          render json: @professor.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor.destroy
    respond_to do |format|
      format.html do
        redirect_to professors_url,
                    notice: 'Professor was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  # GET /professors/search
  def search
    @search = ransack_params
    @professors = ransack_result
  end

  private

  def ransack_params
    Professor.ransack(params[:q])
  end

  def ransack_result
    @search.result
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_professor
    @professor = Professor.find(params[:id])
  end

  def set_course
    @course = Course.find(params[:course_id])
  end

  # Only allow a list of trusted parameters through.
  def professor_params
    params.require(:professor).permit(
      :first_name,
      :last_name,
      :full_name,
      :display_name,
      :cv_url,
      :tamu_dir_title,
      :tamu_dir_dept,
      :tamu_dir_email
    )
  end
end

app/helpers/professor_helper.rb
# frozen_string_literal: true

module ProfessorHelper; end

app/helpers/professors_helper.rb
# frozen_string_literal: true

module ProfessorsHelper; end

app/views/professors/_form.html.erb
<%= form_with(model: professor, local: true) do |form| %>
  <% if professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
        <% professor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :full_name %>
    <%= form.text_field :full_name %>
  </div>

  <div class="field">
    <%= form.label :display_name %>
    <%= form.text_field :display_name %>
  </div>

  <div class="field">
    <%= form.label :cv_url %>
    <%= form.text_field :cv_url %>
  </div>

  <div class="field">
    <%= form.label :tamu_dir_title %>
    <%= form.text_field :tamu_dir_title %>
  </div>

  <div class="field">
    <%= form.label :tamu_dir_dept %>
    <%= form.text_field :tamu_dir_dept %>
  </div>

  <div class="field">
    <%= form.label :tamu_dir_email %>
    <%= form.text_field :tamu_dir_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/professors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professors</h1>

<table>
  <thead>
    <tr>
<!--       <th>First name</th>
      <th>Last name</th>
      <th>Full name</th> -->
      <th>Display name</th>
     <!--  <th>Cv url</th>
      <th>Tamu dir title</th>
      <th>Tamu dir dept</th>
      <th>Tamu dir email</th> -->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @professors.each do |professor| %>
      <tr>
        <!-- <td><%= professor.first_name %></td>
        <td><%= professor.last_name %></td>
        <td><%= professor.full_name %></td> -->
        <td><%= professor.display_name %></td>
        <!-- <td><%= professor.cv_url %></td>
        <td><%= professor.tamu_dir_title %></td>
        <td><%= professor.tamu_dir_dept %></td>
        <td><%= professor.tamu_dir_email %></td> -->
        <td><%= link_to 'Show', professor %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Professor', new_professor_path %>

app/views/professors/new.html.erb
<h1>New Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Back', professors_path %>

app/views/professors/search.html.erb
<%= render 'partials/nav' %>

<p id="notice"><%= notice %></p>

<div class="flex-container">
  <div class="courses-search">  
    <%= render 'partials/searchcontainers' %>

    <table class="search-prof-results">
      <thead>
      <tr>
    <!--    
        <th>First name</th>
        <th>Last name</th> 
        <th>Full name</th>
        <th>Cv url</th>
        <th>Tamu dir title</th>
        <th>Tamu dir email</th>
      -->
        <th>Name</th>
        <th colspan=2>Department</th>
      </tr>
      </thead>

      <tbody>
      <% @professors.each do |professor| %>
        <tr>

    <!--
          <td><%= professor.first_name %></td>
          <td><%= professor.last_name %></td>
          <td><%= professor.full_name %></td>
          <td><%= professor.tamu_dir_title %></td>
          <td><%= professor.cv_url %></td>
          <td><%= professor.tamu_dir_email %></td>
    -->
          <td><%= professor.display_name %></td>
          <td><%= professor.tamu_dir_dept %></td>
          <td class="view-btn"><%= link_to 'Show', professor %></td>
        </tr>
      <% end %>
      </tbody>
    </table>


  </div>
</div>

<%= render "partials/footer" %>

app/views/professors/show.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<%= render 'partials/nav' %>

<p id="notice"><%= notice %></p>
<div class="flex-container">
  <div class="professor-course-container">
    <div class="flex-row">
      <div class="flex-col-50" style="display: inline">
        <h1><%= @professor.display_name %></h1>
        <h4><%= @professor.tamu_dir_title %>
          <% unless @professor.tamu_dir_dept.nil? %>
            <%= @professor.tamu_dir_dept %>
          <% end %>
        </h4>
      </div>
      <div class="flex-col-50">
        <%= link_to 'Write a Review', new_review_path, :class => 'btn btn-primary w-50' %>
      </div>
    </div>
    <div class="flex-row">
      <div class = "review-level-container">
        <h3><%= @avg_review %></h3>
        <div class = "rating-star mr-1">
          <% (1..@avg_review.floor).each do |i| %>
            <span class="fa fa-star checked"></span>
          <% end %>
          <% (1..(5-@avg_review.floor)).each do |i| %>
            <span class="fa fa-star"></span>
          <% end %>
        </div>
      
        <% if @grouped_courses.empty? %>
          <h4>(0 reviews)</h4>
        <% else %>
          <h4>(<%= @num_reviews %> reviews)</h4>
        <% end %>
      </div>
    </div>
  
  <% if current_user && current_user.reviews.exists? %>
    <% if @grouped_courses.empty? %>
      <hr>
      <p>This professor does not have any reviews.</p>
    <% else %>

  <hr>

  <!--highest rated-->
  <div class = "rating-block-container">
    <div class = "review-container">
      <h2>Highest Rated Course</h2>
      <h3>
        <%= link_to @highest_rated_course.dept + ' ' + @highest_rated_course.course_num + ' • ' + @highest_rated_course.name, professor_course_path(@professor, @highest_rated_course), :class=> 'course-title' %>
      </h3>
      <div class = "rating-star">
        <% (1..@highest_rating).each do |i| %>
          <span class="fa fa-star checked"></span>
        <% end %>
        <% (1..@highest_rating_compo).each do |i| %>
          <span class="fa fa-star"></span>
        <% end %>
      </div>
      <h4>
        <%= @highest_rated_course_review.semester + ' ' + @highest_rated_course_review.year.to_s %>
      </h4>
      <p>
        <% if @highest_rated_course_review.professor_other_thoughts.blank? %>
          The reviewer did not leave any thoughts.
        <% else %>
          <%= @highest_rated_course_review.professor_other_thoughts %>
        <% end %>
      </p>
      <div class = "user-agree-container">
        <h5><%= @highest_rated_course_review.get_upvotes.size %> of <%= @highest_rated_course_review.get_upvotes.size+@highest_rated_course_review.get_downvotes.size %></h5>
        <h4>users agree with this review</h4>
      </div>
    </div>
  </div>

  <hr>

  <!--lowest rated-->
  <div class = "rating-block-container">
    <div class = "review-container">
      <h2>Lowest Rated Course</h2>
      <h3><%= link_to @lowest_rated_course.dept + ' ' + @lowest_rated_course.course_num + ' • ' + @lowest_rated_course.name, professor_course_path(@professor, @lowest_rated_course), :class=> 'course-title' %></h3>
      <div class = "rating-star">
        <div class = "rating-star">
          <% (1..@lowest_rating).each do |i| %>
            <span class="fa fa-star checked"></span>
          <% end %>
          <% (1..@lowest_rating_compo).each do |i| %>
            <span class="fa fa-star"></span>
          <% end %>
        </div>
      </div>
      <h4>
        <%= @lowest_rated_course_review.semester + ' ' + @lowest_rated_course_review.year.to_s %>
      </h4>
      <p>
        <% if @lowest_rated_course_review.professor_other_thoughts.blank? %>
          The reviewer did not leave any thoughts.
        <% else %>
          <%= @lowest_rated_course_review.professor_other_thoughts %>
        <% end %>
      </p>
      <div class = "user-agree-container">
        <h5><%= @highest_rated_course_review.get_upvotes.size %> of <%= @highest_rated_course_review.get_upvotes.size+@highest_rated_course_review.get_downvotes.size %></h5>
        <h4>users agree with this review</h4>
      </div>

    </div>
  </div>

  <% end %>

  <hr>

  <!--all course-->
  <div class = "all-course-container">
    <h2>All Courses Taught By <%= @professor.display_name %></h2>
    <% if @grouped_courses.empty? %>
      <p>This professor has not taught any other courses.
    <% else %>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Professor Course Rating</th>
        </tr>
      </thead>

    <tbody>
      <% @grouped_courses.each do |course, _reviews| %>
        <tr>
          <td>
            <h3>
            <%= link_to  course.dept + " " + course.course_num + " " + "•" + " " + course.name, professor_course_path(@professor, course)%>
            </h3>
          </td>
          <td>  
            <div class = "review-level-container">
              <h3><%= avg_rev(_reviews) %></h3>
              <div class = "rating-star">
                <% (1..avg_rev(_reviews).floor).each do |i| %>
                  <span class="fa fa-star checked"></span>
                <% end %>
                <% (1..(5-avg_rev(_reviews).floor)).each do |i| %>
                  <span class="fa fa-star"></span>
                <% end %>
              </div>
            </div> 
          </td>
        </tr>
      <% end %>
    </tbody>

    </table>
    <% end %>


</div>
</div>
<% else %>
    <div class="reviews-locked">
      <%= image_tag 'lock.svg' %>
      <h3>Review to View</h3>
      <p>Leave a review for your professors to view reviews for this professor.</p>
      <%= link_to 'Write a Review', new_review_path, :class => 'btn btn-primary w-50' %>
    </div>
<% end %>

app/views/professors/show_course.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<%= render 'partials/nav' %>

<p id="notice"><%= notice %></p>

<div class="flex-container">
  <div class="professor-course-container">
    <div class="flex-row">
      <div class="flex-col-50" style="display: inline">
        <h1><%= @professor.display_name %></h1>
        <h4><%= @professor.tamu_dir_title %>
          <% unless @professor.tamu_dir_dept.nil? %>
            <%= @professor.tamu_dir_dept %>
          <% end %>
        </h4>
      </div>
      <div class="flex-col-50">
        <%= link_to 'Write a Review', new_review_path, :class => 'btn btn-primary w-50' %>
      </div>
    </div>
    <h2>  <%= @course.dept + " " + @course.course_num + " " + "•" + " " + @course.name %></h2>
    <% if current_user && current_user.reviews.exists? %>
      <% if @grouped_courses.empty? %>
        <p>This professor has not taught any other courses.
      <% else %>
        <h5>Other courses taught by <%= @professor.display_name %></h5>
        <div class="other-classes">
          <% @grouped_courses.each do |course, _reviews| %>
            <%= link_to course.dept + ' ' + course.course_num, professor_course_path(@professor, course) %>
          <% end %>
        </div>
      <% end %>

      <hr>
      <% if @course_reviews.empty? %>
        <p> This professor hasn't taught this course.</p>
      <% else %>
        <h2>Reviews for <%= @course.dept + ' ' + @course.course_num %></h2>
        <% @course_reviews.each do |review| %>


          <div class="review-component">
            <h2><%= @course.dept + ' ' + @course.course_num %></h2>

            <div class="rating-star">
              <% (1..review.overall_rating.floor).each do |i| %>
                <span class="fa fa-star checked"></span>
              <% end %>
              <% (1..(5 - review.overall_rating.floor)).each do |i| %>
                <span class="fa fa-star"></span>
              <% end %>
            </div>

            <div class="review-body">
              <!-- expected grade -->
              <h3><b>Expected Grade:</b></h3>
              <h3 style="padding-right: 20px;"><%= review.letter_grade %></h3>
              <h3><b>Attendance:</b></h3>
              <h3 style="padding-right: 20px;">
                <% if review.attendance_mandatory %>
                  Mandatory
                <% else %>
                  Optional
                <% end %>
              </h3>
              <h3><b>Textbook:</b></h3>
              <h3 style="padding-right: 20px;">
                <% if review.used_textbook %>
                  Yes
                <% else %>
                  No
                <% end %>
              </h3>
            </div>

            <% if review.course_other_thoughts.blank? %>
              <p style="color: #777777;">The reviewer did not leave any thoughts.</p>
            <% else %>
              <p><%= review.course_other_thoughts %></p>
            <% end %>

            <div class="review-footer">
              <div class="user-agree-container">
                <p><%= link_to review_upvote_path(review), id: "upvote_link_" + review.id.to_s, method: :put do %>
                    <%= image_tag 'thumb-up.svg' %>
                  <% end %>
                  <%= link_to review_downvote_path(review), id: "downvote_link_" + review.id.to_s, method: :put do %>
                    <%= image_tag 'thumb-down.svg' %>
                  <% end %>
                </p>
                <h5><%= review.get_upvotes.size %> of <%= review.votes_for.size %></h5>
                <h4>users agree</h4>
              </div>
              <div class="report-container">
                <%= render partial: "partials/report_modal", locals: {review_id: review.id} %>
              </div>
            </div>

          </div>
          <br/>
        <% end %>
      <% end %>
    <% else %>
      <div class="reviews-locked">
        <%= image_tag 'lock.svg' %>
        <h3>Review to View</h3>
        <p>Leave a review for your professors to view reviews for this professor.</p>
        <%= link_to 'Write a Review', new_review_path, :class => 'btn btn-primary w-50' %>
      </div>
    <% end %>

  </div>
</div>