config/routes.rb
Rails.application.routes.draw do
  root 'login#index'

  resources :professors, except: %i[edit create update destroy] do
    collection { get 'search' }
    get '/courses/:course_id', to: 'professors#show_course', as: 'course'
  end
  resources :courses, except: %i[edit create update destroy] do
    collection { get 'search' }
  end
  get 'login' => 'login#index'
  delete '/logout', to: 'sessions#destroy'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'search' => 'search#index'

  resources :reviews, except: %i[index] do
    post '/report' => 'reviews#report'
    put 'upvote', to: 'reviews#upvote'
    put 'downvote', to: 'reviews#downvote'
  end
  resources :sessions, only: %i[create delete]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
# frozen_string_literal: true

class CoursesController < ApplicationController
  before_action :set_course, only: %i[show edit update destroy]
  before_action :set_professor
  helper_method :avg_rev

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def avg_rev(reviews)
    sum = 0
    reviews.each { |a| sum += a.overall_rating }
    sum.to_f / reviews.length
  end

  def show
    @avg_course =
      if @course.reviews.blank?
        0
      else
        @course.reviews.average(:overall_rating).round(2)
      end
    @grouped_prof = @course.reviews.group_by(&:professor)
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit; end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html do
          redirect_to @course, notice: 'Course was successfully created.'
        end
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json do
          render json: @course.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html do
          redirect_to @course, notice: 'Course was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json do
          render json: @course.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html do
        redirect_to courses_url, notice: 'Course was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  # GET /courses/search
  def search
    @search = ransack_params
    @courses = ransack_result
  end

  private

  def ransack_params
    Course.ransack(params[:q])
  end

  def ransack_result
    @search.result
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

  def set_professor
    @professor = Professor.first
  end

  # Only allow a list of trusted parameters through.
  def course_params
    params.require(:course).permit(:dept, :course_num, :name)
  end
end

app/helpers/courses_helper.rb
# frozen_string_literal: true

module CoursesHelper; end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :dept %>
    <%= form.text_field :dept %>
  </div>

  <div class="field">
    <%= form.label :course_num %>
    <%= form.text_field :course_num %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Dept</th>
      <th>Course num</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.dept %></td>
        <td><%= course.course_num %></td>
        <td><%= course.name %></td>
        <td><%= link_to 'Show', course %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/search.html.erb
<%= render 'partials/nav' %>

<p id="notice"><%= notice %></p>
<div class="flex-container">
  <div class="courses-search">
  <%= render 'partials/searchcontainers' %>

    <table class="search-results">
      <thead>
      <tr>
        <th>Dept</th>
        <th>Course</th>
        <th>Name</th>
        <th></th>
      </tr>
      </thead>

      <tbody>
      <% @courses.each do |course| %>
        <tr>
          <td width="10%"><%= course.dept %></td>
          <td width="12%"><%= course.course_num %></td>
          <td width="68%">
            <%= course.name %>
            <p class="course-description">
              <%= course.description %>
            </p>
          </td>
          <td width="10%" class="view-btn"><%= link_to 'Show', course %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <br>
  </div>
</div>


<%= render "partials/footer" %>

app/views/courses/show.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<p id="notice"><%= notice %></p>

<div class="flex-container">
  <div class="courses-search">
    <!--course name-->
    <div class="course-name">
      <h1>
        <%= @course.dept + " " + @course.course_num + " " + "•" + " " + @course.name %>
      </h1>
    </div>


    <!--course rating & description-->
    <div class="course-rating-des">
      <div class="flex-row">
        <!--rating-->
        <div class="flex-col-50" style="display: inline">

          <h2>
            Course Ratings
          </h2>
          <h3><%=@avg_course%></h3>
          <div class = "rating-star">
            <% (1..@avg_course.floor).each do |i| %>
              <span class="fa fa-star checked"></span>
            <% end %>

            <% (1..(5-@avg_course.floor)).each do |i| %>
              <span class="fa fa-star"></span>
            <% end %>
          </div>
        </div>


        <!--description-->
        <div class="flex-col-50">
          <h2>
            Course Description
          </h2>
          <p> <%= @course.description %> </p>
        </div>
      </div>
    </div>
    <!--professors-->
    <div class="course-prof">

      <h2>Professors</h2>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th colspan="5">Rating</th>
          </tr>
        </thead>
        <tbody>
          <% if @grouped_prof.blank? %>
            <tr>
              <td>
                <p>No reviews have been submitted for this course.</p>
              </td>
            </tr>
          <% else %>
          <% @grouped_prof.each do |professor, _reviews| %>
            <tr>
              <td>
                <h3>
                <%= link_to professor.full_name, professor_course_path(professor, @course) %>
                </h3>
              </td>

              <td class="table-padding">   </td>

              <td>
                <div class = "review-level-container">
                  <div class = "rating-star mr-1">
                    <% (1..avg_rev(_reviews).floor).each do |i| %>
                      <span class="fa fa-star checked"></span>
                    <% end %>

                    <% (1..(5-avg_rev(_reviews).floor)).each do |i| %>
                      <span class="fa fa-star"></span>
                    <% end %>
                  </div>
                  <% if @grouped_prof.empty? %>
                    <h4 class="d-sm-none">(0 reviews)</h4>
                  <% else %>
                    <h4 class="d-sm-none">(<%= _reviews.length %> reviews)</h4>
                  <% end %>
                </div>
              </td>
              <td class="a-write">
                <%= link_to 'Write a Review', new_review_path, :class => 'btn-table btn-primary w-90' %>
              </td>
            </tr>
          <% end %>

        </tbody>
        <% end %>

      </table>


    </div>