config/routes.rb
Rails.application.routes.draw do
  root 'login#index'

  resources :professors, except: %i[edit create update destroy] do
    collection { get 'search' }
    get '/courses/:course_id', to: 'professors#show_course', as: 'course'
  end
  resources :courses, except: %i[edit create update destroy] do
    collection { get 'search' }
  end
  get 'login' => 'login#index'
  delete '/logout', to: 'sessions#destroy'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'search' => 'search#index'

  resources :reviews, except: %i[index] do
    post '/report' => 'reviews#report'
    put 'upvote', to: 'reviews#upvote'
    put 'downvote', to: 'reviews#downvote'
  end
  resources :sessions, only: %i[create delete]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
# frozen_string_literal: true

class ReviewsController < ApplicationController
  before_action :set_professor
  before_action :set_course
  before_action :set_review, only: %i[show edit update destroy]

  def upvote
    @review = Review.find(params[:review_id])
    if current_user.blank?
      redirect_to professor_course_path(
                    @review.professor_id,
                    @review.course_id
                  ),
                  notice: 'You must be logged in.'
    else
      if current_user.voted_up_for? @review
        @review.unliked_by current_user
      else
        @review.upvote_from current_user
      end
      redirect_to professor_course_path(@review.professor_id, @review.course_id)
    end
  end

  def downvote
    @review = Review.find(params[:review_id])
    if current_user.blank?
      redirect_to professor_course_path(
                    @review.professor_id,
                    @review.course_id
                  ),
                  notice: 'You must be logged in.'
    else
      if current_user.voted_down_for? @review
        @review.undisliked_by current_user
      else
        @review.downvote_from current_user
      end
      redirect_to professor_course_path(@review.professor_id, @review.course_id)
    end
  end

  def report
    @review = Review.find(params[:review_id])
    if params[:reason].blank?
      redirect_to review_path(@review),
                  notice: 'Unable to complete your request.'
    else
      reason = params[:reason]
      other_input = params[:other_input]

      url = review_path(@review.id)
      begin
        UserMailer.report_email(
          reason,
          other_input,
          url,
          @review.professor_id,
          @review.course_id
        )
          .deliver_now
      rescue StandardError
        redirect_to url, notice: 'Unable to complete your request.'
      else
        redirect_to url, notice: 'Review was successfully reported.'
      end
    end
  end

  # GET /reviews
  # GET /reviews.json
  def index; end

  # GET /reviews/1
  # GET /reviews/1.json
  def show; end

  # GET /reviews/new
  def new
    if current_user.blank?
      redirect_to root_path, notice: 'You must be logged in to create a review.'
    else
      @courses = load_courses
      @professors = load_professors
      @review = Review.new
    end
  end

  # GET /reviews/1/edit
  def edit
    @courses = load_courses
    @course_id = @review.course_id
    @professors = load_professors
    @professor_id = @review.professor_id
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    if !params[:course_id].blank? && !params[:professor_id].blank?
      @review.course_id = params[:course_id]
      @review.professor_id = params[:professor_id]
      @review.authuser_id = current_user.id
      respond_to do |format|
        if @review.save
          format.html do
            redirect_to professor_course_path(
                          @review.professor_id,
                          @review.course_id
                        ),
                        notice: 'Your review was submitted'
          end
          format.json { render :show, status: :created, location: @review }
        else
          @professors = load_professors
          @courses = load_courses
          format.html { render :new }
          format.json do
            render json: @review.errors, status: :unprocessable_entity
          end
        end
      end
    else
      redirect_to new_review_path, notice: 'Fill out all required fields'
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    if current_user.blank?
      redirect_to professor_course_path(
                    @review.professor_id,
                    @review.course_id
                  ),
                  notice: 'You must be
      logged in to update a review.'
    else
      @review.authuser_id = current_user.id
      respond_to do |format|
        if @review.update(review_params)
          format.html do
            redirect_to professor_course_path(
                          @review.professor_id,
                          @review.course_id
                        ),
                        notice: 'Review was successfully updated.'
          end
          format.json { render :show, status: :ok, location: @review }
        else
          format.html do
            @courses = load_courses
            @professors = load_professors
            render :edit
          end
          format.json do
            render json: @review.errors, status: :unprocessable_entity
          end
        end
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    prof_id = @review.professor_id
    @review.destroy
    respond_to do |format|
      format.html do
        redirect_to professor_path(prof_id),
                    notice: 'Review was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_review
    @review = Review.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def review_params
    params.require(:review).permit(
      :overall_rating,
      :letter_grade,
      :semester,
      :year,
      :course_required,
      :interesting,
      :difficult,
      :standardized_course,
      :course_other_thoughts,
      :used_textbook,
      :attendance_mandatory,
      :course_format,
      :cared_about_material,
      :open_to_questions,
      :cared_about_students,
      :clear_grading,
      :homework_heavy,
      :clear_explanations,
      :fast_grading,
      :professor_other_thoughts,
      :professor_id,
      :course_id
    )
  end

  def set_professor
    unless params[:professor_id].blank?
      @professor = Professor.find(params[:professor_id])
    end
  end

  def set_course
    @course = Course.find(params[:course_id]) unless params[:course_id].blank?
  end

  def load_courses
    Course.all.order(:dept, :course_num)
  end

  def load_professors
    Professor.all.order(:full_name)
  end
end

app/helpers/reviews_helper.rb
# frozen_string_literal: true

module ReviewsHelper; end

app/views/reviews/_form.html.erb
<%= form_for @review do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.full_messages.each_with_index do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div id="selectProfessor">
    <%= form.label :professor_id %>
    <% unless @professor_id.nil? %>
      <%= select_tag(:professor_id, options_from_collection_for_select(@professors, :id, :full_name, :selected => @professor_id), :required => true) %>
    <% else %>
      <%= select_tag(:professor_id, options_from_collection_for_select(@professors, :id, :full_name), :required => true, :prompt => 'Select a Professor') %>
    <% end %>
  </div>

  <div id="selectCourse">
    <%= form.label :course_id %>
    <% unless @course_id.nil? %>
      <%= select_tag(:course_id, options_from_collection_for_select(@courses, :id, :full_course_name, :selected => @course_id), :required => true) %>
    <% else %>
      <%= select_tag(:course_id, options_from_collection_for_select(@courses, :id, :full_course_name), :required => true, :prompt => 'Select a Course') %>
    <% end %>
  </div>


  <div id="field radio-inline">
    <%= form.label :overall_rating %>
    <% (1..5).each_with_index do |i| %>
      <%= form.radio_button :overall_rating, i %> <%= i %> <br/>
    <% end %>
  </div>

  <div id="letterGrade">
    <%= form.label :letter_grade %>

    <%= form.select :letter_grade, %w[A B C D F Q S U] %>
  </div>

  <div id="semester">
    <%= form.label :semester %>

    <%= form.select :semester, %w[Spring Summer Fall] %>
  </div>

  <div id="year">
    <%= form.label :year %>
    <%= form.select :year, 2000..Date.today.year %>
  </div>

  <div id="field" class="checkbox-style">
    <%= form.label :course_required %>
    <%= form.check_box :course_required %>
  </div>


  <hr>
  <h4>Course Review</h4>

  <div id="field">
    <%= form.label :interesting %>
    <% ['Strongly Disagree', 'Slightly Disagree', 'Neither Disagree nor Agree', 'Slightly Agree', 'Strongly Agree'].each_with_index do | elem, i | %>
      <%= form.radio_button :interesting, i+1 %> <%= elem %> <br/>
    <% end %>

  </div>

  <div id="difficult">
    <%= form.label :difficult %>
    <% ['Strongly Disagree', 'Slightly Disagree', 'Neither Disagree nor Agree', 'Slightly Agree', 'Strongly Agree'].each_with_index do | elem, i | %>
      <%= form.radio_button :difficult, i+1 %> <%= elem %> <br/>
    <% end %>
  </div>

  <div id="field" class="checkbox-style">
    <%= form.label :standardized_course %>
    <%= form.check_box :standardized_course %>
  </div>

  <div id="courseOtherThoughts">
    <%= form.label :course_other_thoughts %>
    <%= form.text_field :course_other_thoughts, :placeholder => 'ex. Loved the class' %>
  </div>


  <hr>
  <h4>Professor Review</h4>

  <div id="field" class="checkbox-style">
    <%= form.label :used_textbook %>
    <%= form.check_box :used_textbook %>
  </div>

  <div id="field"  class="checkbox-style">
    <%= form.label :attendance_mandatory %>
    <%= form.check_box :attendance_mandatory %>
  </div>

  <div id="courseFormat">
    <%= form.label :course_format %>
    <%= form.select :course_format, %w[Exam Project Homework] %>
  </div>

  <div id="caredAboutMaterial">
    <%= form.label :cared_about_material %>
    <% ['Strongly Disagree', 'Slightly Disagree', 'Neither Disagree nor Agree', 'Slightly Agree', 'Strongly Agree'].each_with_index do | elem, i | %>
      <%= form.radio_button :cared_about_material, i+1 %> <%= elem %> <br/>
    <% end %>
  </div>

  <div id="openToQuestions">
    <%= form.label :open_to_questions %>
    <% ['Strongly Disagree', 'Slightly Disagree', 'Neither Disagree nor Agree', 'Slightly Agree', 'Strongly Agree'].each_with_index do | elem, i | %>
      <%= form.radio_button :open_to_questions, i+1 %> <%= elem %> <br/>
    <% end %>
  </div>

  <div id="caredAboutStudents">
    <%= form.label :cared_about_students %>
    <% ['Strongly Disagree', 'Slightly Disagree', 'Neither Disagree nor Agree', 'Slightly Agree', 'Strongly Agree'].each_with_index do | elem, i | %>
      <%= form.radio_button :cared_about_students, i+1 %> <%= elem %> <br/>
    <% end %>
  </div>

  <div id="clearGrading">
    <%= form.label :clear_grading %>
    <% ['Strongly Disagree', 'Slightly Disagree', 'Neither Disagree nor Agree', 'Slightly Agree', 'Strongly Agree'].each_with_index do | elem, i | %>
      <%= form.radio_button :clear_grading, i+1 %> <%= elem %> <br/>
    <% end %>
  </div>

  <div id="homeworkHeavy">
    <%= form.label :homework_heavy %>
    <% ['Strongly Disagree', 'Slightly Disagree', 'Neither Disagree nor Agree', 'Slightly Agree', 'Strongly Agree'].each_with_index do | elem, i | %>
      <%= form.radio_button :homework_heavy, i+1 %> <%= elem %> <br/>
    <% end %>
  </div>

  <div id="clearExplanations">
    <%= form.label :clear_explanations %>
    <% ['Strongly Disagree', 'Slightly Disagree', 'Neither Disagree nor Agree', 'Slightly Agree', 'Strongly Agree'].each_with_index do | elem, i | %>
      <%= form.radio_button :clear_explanations, i+1 %> <%= elem %> <br/>
    <% end %>
  </div>

  <div id="fastGrading">
    <%= form.label :fast_grading %>
    <% ['Strongly Disagree', 'Slightly Disagree', 'Neither Disagree nor Agree', 'Slightly Agree', 'Strongly Agree'].each_with_index do | elem, i | %>
      <%= form.radio_button :fast_grading, i+1 %> <%= elem %> <br/>
    <% end %>
  </div>

  <div id="professorOtherThoughts">
    <%= form.label :professor_other_thoughts %>
    <%= form.text_field :professor_other_thoughts, :placeholder => 'ex. Helpful office hours' %>
  </div>


  <div id="actions" class="mt-3">
    <%= form.submit :class => "btn btn-primary w-50" %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>
<table>
  <thead>
    <tr>
      <th>Overall rating</th>
      <th>Letter grade</th>
      <th>Semester</th>
      <th>Year</th>
      <th>Course required</th>
      <th>Interesting</th>
      <th>Difficult</th>
      <th>Standardized course</th>
      <th>Course other thoughts</th>
      <th>Used textbook</th>
      <th>Attendance mandatory</th>
      <th>Course format</th>
      <th>Cared about material</th>
      <th>Open to questions</th>
      <th>Cared about students</th>
      <th>Clear grading</th>
      <th>Homework heavy</th>
      <th>Clear explanations</th>
      <th>Fast grading</th>
      <th>Professor other thoughts</th>
      <th>Professor</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.overall_rating %></td>
        <td><%= review.letter_grade %></td>
        <td><%= review.semester %></td>
        <td><%= review.year %></td>
        <td><%= review.course_required %></td>
        <td><%= review.interesting %></td>
        <td><%= review.difficult %></td>
        <td><%= review.standardized_course %></td>
        <td><%= review.course_other_thoughts %></td>
        <td><%= review.used_textbook %></td>
        <td><%= review.attendance_mandatory %></td>
        <td><%= review.course_format %></td>
        <td><%= review.cared_about_material %></td>
        <td><%= review.open_to_questions %></td>
        <td><%= review.cared_about_students %></td>
        <td><%= review.clear_grading %></td>
        <td><%= review.homework_heavy %></td>
        <td><%= review.clear_explanations %></td>
        <td><%= review.fast_grading %></td>
        <td><%= review.professor_other_thoughts %></td>
        <td><%= review.professor_id %></td>
        <td><%= review.course_id %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <button class="btn btn-primary" id="myBtn">Report Review</button>
    <%= render "partials/modal" %>
  </tbody>
</table><br>
<%= link_to 'New Review', new_review_path %>
<%= render "partials/footer" %>

app/views/reviews/new.html.erb
<%= render "partials/nav" %>

<div class="flex-container review-container">
    <div class="reviewform-container">
        <h2>Write a Review</h2>
        <%= render 'form', review: @review %>
    </div>
</div>

app/views/reviews/show.html.erb
<h1 id="notice"><%= notice %></h1>
<h1>Reviews</h1>
<p>
  <strong>Overall rating:</strong>
  <%= @review.overall_rating %>
</p>

<p>
  <strong>Letter grade:</strong>
  <%= @review.letter_grade %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @review.semester %>
</p>

<p>
  <strong>Year:</strong>
  <%= @review.year %>
</p>

<p>
  <strong>Course required:</strong>
  <%= @review.course_required %>
</p>

<p>
  <strong>Interesting:</strong>
  <%= @review.interesting %>
</p>

<p>
  <strong>Difficult:</strong>
  <%= @review.difficult %>
</p>

<p>
  <strong>Standardized course:</strong>
  <%= @review.standardized_course %>
</p>

<p>
  <strong>Course other thoughts:</strong>
  <%= @review.course_other_thoughts %>
</p>

<p>
  <strong>Used textbook:</strong>
  <%= @review.used_textbook %>
</p>

<p>
  <strong>Attendance mandatory:</strong>
  <%= @review.attendance_mandatory %>
</p>

<p>
  <strong>Course format:</strong>
  <%= @review.course_format %>
</p>

<p>
  <strong>Cared about material:</strong>
  <%= @review.cared_about_material %>
</p>

<p>
  <strong>Open to questions:</strong>
  <%= @review.open_to_questions %>
</p>

<p>
  <strong>Cared about students:</strong>
  <%= @review.cared_about_students %>
</p>

<p>
  <strong>Clear grading:</strong>
  <%= @review.clear_grading %>
</p>

<p>
  <strong>Homework heavy:</strong>
  <%= @review.homework_heavy %>
</p>

<p>
  <strong>Clear explanations:</strong>
  <%= @review.clear_explanations %>
</p>

<p>
  <strong>Fast grading:</strong>
  <%= @review.fast_grading %>
</p>

<p>
  <strong>Professor other thoughts:</strong>
  <%= @review.professor_other_thoughts %>
</p>

<p>
  <strong>Professor:</strong>
  <%= Professor.find(@review.professor_id).display_name %>
</p>

<p>
  <strong>Course:</strong>
  <%= Course.find(@review.course_id).full_course_name %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', professor_path(@review.professor_id) %>

<%= render partial: "partials/report_modal", locals: {review_id: @review.id} %>